version: "2"

services:
  pharmaconnect-db:
    image: mysql
    restart:
      unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=pharmaconnect
      - MYSQL_TCP_PORT=3306
    ports:
      - 3306:3306
    

  pharmaconnect-app:
    depends_on:
      - pharmaconnect-db
    build: 
      context: .
      dockerfile: Dockerfile
    restart:
      unless-stopped
    command: sh -c "npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npm start"
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/app
